config/routes.rb
Rails.application.routes.draw do
  root to: "groups#index"
  get "/" => "groups#index", as: :groups
  get "/groups/:id" => "groups#show", as: :group
  get "/groups/:id/add" => "groups#add_file", as: :add_file
  post "/groups/:id/add" => "groups#create_file", as: :create_file

  namespace :admin do
    resources :users
    resources :groups

    root to: "users#index"
  end

  devise_for :users
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :uploads
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :group
  has_attached_file :zoop,
    validate_media_type: false,
    preserve_files: false,
    processors: [:encryptor],
    styles: {original: {}}
  do_not_validate_attachment_file_type :zoop
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :validatable, :authentication_keys => [:username]

  validates :public_key, presence: true

  has_many :owned_groups, foreign_key: "owner_id", class_name: "Group"
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_user!

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/group_users_controller.rb
module Admin
  class GroupUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = GroupUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   GroupUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/groups_controller.rb
module Admin
  class GroupsController < Admin::ApplicationController
    before_action :filter_users, except: [:index, :new, :create]

    def filter_users
      group = Group.find(params["id"])
      unless current_user.id == group.owner_id
        flash[:error] = "You are not that group's owner!"
        redirect_to admin_groups_path
      end
    end
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Group.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Group.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :filter_users, except: [:index, :new, :create]

    def filter_users
      unless current_user.id == params["id"].to_i
        flash[:error] = "You are not that user!"
        redirect_to admin_users_path
      end
    end
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.includes(:uploads).find(params["id"])
    if current_user && @group.users.include?(current_user)
      @encoded_symetric_key = encode_key(current_user, @group.secret_key)
    end
  end

  def encode_key(user, secret_key)
    public_key = OpenSSL::PKey::RSA.new(user.public_key)
    Base64.encode64(public_key.public_encrypt(secret_key))
  end

  def add_file
    @group = Group.find(params["id"])
    filter_users
    @upload = Upload.new
  end

  def gen_iv
    SecureRandom.hex()
  end

  def create_file
    @group = Group.find(params["id"])

    filter_users

    upload = Upload.new(file_params)

    if upload.save!
      redirect_to group_path(@group.id)
    else
      redirect_to add_file_path(@group.id)
    end
  end

  private

  def file_params
    params["upload"]["iv"] = gen_iv
    params.require(:upload).permit(:iv, :group_id, :zoop)
  end

  def filter_users
    unless @group && @group.owner_id == current_user.id
      flash[:error] = "You are not that group's owner!"
      redirect_to admin_groups_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/add_file.html.erb
<h3>New Upload</h3>

<%= simple_form_for @upload, url: create_file_path(@group.id) do |form| %>
  <%= form.input :zoop, as: :file %>
  <%= form.hidden_field :group_id, value: @group.id %>
  <%= form.button :submit %>
<% end %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>Group</th>
      <th>Files</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.uploads.count %> files</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/show.html.erb
<h1>Group <%= @group.name %></h1>
<% if @encoded_symetric_key %>
  <p>To decode the symmetric key:<br>
  <code>echo <%= @encoded_symetric_key %> | base64 --decode | openssl rsautl -decrypt -inkey your_private_key.pem</code>
  </p>
  <p>To decrypt a file use the exectuable in <code>exe</code>:<br>
  <code>alohomora [decrypted_symmetric_key] [file_specific_initialization_vector] [path_to_encrypted_file]</code>
  </p>
<% end %>
<table class="table table-responsive">
  <thead>
    <tr>
      <th>File</th>
      <th>Initialization Vector</th>
      <th><%= link_to "Upload File", add_file_path(@group) %></th>
    </tr>
  </thead>
  <tbody>
    <% @group.uploads.each do |upload| %>
      <tr>
        <td><%= link_to upload.zoop_file_name, upload.zoop.url(:original, false), targer: "_blank" %></td>
        <td><%= upload.iv %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Alohomora", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to "Admin", admin_groups_path %></li>
        <li><%= link_to "Groups", groups_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alohomora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>